### ISSUE TITLE
Transfer to an organization

### ISSUE THREAD

**Issue by Changaco** [Legilibre/legi.py#1]
À ma connaissance nous sommes 3 à bosser sur la conversion de la base LEGI: moi, @Seb35 et @steeve. Je propose de regrouper nos projets dans une organisation commune.

**Comment by Seb35** [comment]
Sur mes projets, je voulais depuis longtemps faire évoluer mon code vers une bibliothèque (idée proche de legi.py). Coïncidence, j’y ai travaillé hier et ai quasiment fini la partie "Téléchargement des bases OpenData (JORF, LEGI, etc.)" ; c’est du Python et je commiterai sous peu. Je compte faire un nouveau dépôt qui sera dérivé de Archéo Lex.

Sur une organisation commune, quelle serait l’idée ? Juste donner de la visibilité aux projets ? Fédérer une communauté ?
Autour du droit ouvert, il y a déjà des communautés :
* [OpenLaw](http://openlaw.fr) rassemblant les principaux acteurs de l’édition juridique française (j’ai fait une présentation d’Archéo Lex dans ce cadre en février dernier)
* [ShareLex](http://www.sharelex.org)
* [Regards Citoyens](http://www.regardscitoyens.org) et en particulier La Fabrique de la Loi -- je les avais rapidement rencontré en septembre 2014 pour parler de droit ouvert/Archéo Lex.
* [Alinéa](http://alineabyluxia.fr), non-libre mais avec les mêmes données et une technique proche

De mon côté, j’ai ouvert une [liste de discussion](https://archeo-lex.fr/listes) en février dernier sur le projet Archéo Lex, mais il n’y a quasiment pas d’activité pour l’instant.

Comme ça, à vif, je suis pas trop sûr que créer une organisation soit vraiment intéressant question visibilité/duplication des efforts, peut-être plutôt se rapprocher d’organisations existantes. En fait, surtout, il faudrait s’organiser pour faire des produits logiciels de bonne qualité (quels qu’ils soient : bibliothèques, interfaces de visualisation, etc.).

PS : j’avais fait un [tutoriel sur la lecture de la base LEGI](https://github.com/Seb35/Archeo-Lex/wiki/Base_LEGI), me disant que ça servirait au moins sinon plus que le code lui-même. Ça peut te servir pour legi.py -- les autres bases sont très similaires à LEGI dans leur organisation (souvent en plus simple), sauf KALI qui a une spécificité supplémentaire (les conteneurs).

**Comment by Changaco** [comment]
L'idée est de regrouper nos projets dans un même endroit, et avec un peu de chance ça générera une synergie.

On n'est pas obligé de créer une organisation, on peut demander à @regardscitoyens s'ils veulent bien créer une équipe pour nous par exemple.

**Comment by fgallaire** [comment]
Voilà donc je propose Légilibre, qui pourrait faire un lieu commun pour tous les projets libres autour de la base LEGI (et plus généralement du droit).

**Comment by Changaco** [comment]
OK pour moi. Qu'en penses-tu @Seb35 ?

**Comment by Changaco** [comment]
Transfert effectué, legi.py fait désormais partie de Légilibre. :tada:
