### ISSUE TITLE
Drapeau "italien" ? :O

### ISSUE THREAD

**Issue by tantale** [Legilibre/legi.py#26]
Bonjour à toute l'équipe,

Pourquoi avez-vous utilisé les couleurs de l'Italie pur votre [logo](https://avatars3.githubusercontent.com/u/6777462?s=200&v=4) ?

– Laurent LAPORTE.

**Comment by Changaco** [comment]
Le logo de Légilibre n'est pas de moi (ping @fgallaire), mais dans ce contexte il est évident que le vert et le rouge sont les couleurs d'un "diff", pas celles de l'Italie.

![capture d'écran d'un diff GitHub](https://user-images.githubusercontent.com/1581590/36078991-4e04c8fe-0f7e-11e8-8b31-ed6e55ba1c21.png)

**Comment by fgallaire** [comment]
Merci @Changaco c'est exactement ça ;-)
