### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by revolunet** [Legilibre/legi.py#28]
Bonjour, si ça peut servir à quelqu'un j'ai crée un Dockerfile qui permet de lancer directement `legi.py` sans avoir à installer les dépendances sur son système : https://github.com/revolunet/legi.py-docker

**Comment by Changaco** [comment]
Discussion connexe : https://github.com/Legilibre/salon/issues/16

**Comment by revolunet** [comment]
Je close, pour ceux qui ont besoin il y a [legi-postgres](https://github.com/Legilibre/legi-postgres) qui contient un [Dockerfile](https://github.com/Legilibre/legi-postgres/blob/master/Dockerfile-legi) pour legi.py.

Voir également les scripts de déploiement ici : https://github.com/Legilibre/deploiement
