### ISSUE TITLE
Python 2

### ISSUE THREAD

**Issue by Changaco** [Legilibre/legi.py#30]
Pour info je prévois de supprimer le support de python 2.7 dans legi.py d'ici deux ans maximum.

**Comment by lel-amri** [comment]
Voici ce qui vient de tomber sur la ML de Python: https://mail.python.org/pipermail/python-list/2018-March/731770.html
Fin du support pour Python 2.7: 1er Janvier 2020

**Comment by Seb35** [comment]
Pour info je viens de faire passer Archéo Lex à Python3, notamment pour avoir une meilleure gestion des strings/Unicode, et n’ai pas rencontré de problèmes vis-à-vis de legi.py.
