### ISSUE TITLE
Échec du téléchargement

### ISSUE THREAD

**Issue by Changaco** [Legilibre/legi.py#36]
Le serveur FTP de la DILA (<ftp://echanges.dila.gouv.fr/>) ne fonctionne plus correctement, il renvoie des erreurs "550 Failed to change directory" quand le client essaie d'accéder à certains dossiers, dont LEGI.

**Comment by cottinstef** [comment]
DSI DILA prévenue. Incidents identifiés sur les serveurs FTP à la DILA, en cours de résolution ce matin.

**Comment by Changaco** [comment]
Le problème est résolu. :slightly_smiling_face:
