### ISSUE TITLE
article présent dans LEGI, mais absent dans le sqlite

### ISSUE THREAD

**Issue by revolunet** [Legilibre/legi.py#42]
Bonjour,

Je me permets de remonter un petit souci, qui me semble-t-il vient de la conversion dans SQLite.

Article 1221-18 dans le code du travail

 - présent sur LegiFrance : https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006072050&idArticle=LEGIARTI000037064963&dateTexte=&categorieLien=id
 - présent dans le fichier DILA `Freemium_legi_global_20180706-113123.tar.gz` (dans `legi/global/code_et_TNC_en_vigueur/code_en_vigueur/LEGI/TEXT/00/00/06/07/20/LEGITEXT000006072050/article/LEGI/ARTI/00/00/37/06/49/LEGIARTI000037064963.xml`)

Dans legi.sqlite : 
 - je ne le retrouve pas dans la table des articles : `select * from articles where id="LEGIARTI000037064963"` :
 - il est pourtant bien présent dans le sommaire :  `select * from `sommaires` where `parent` = 'LEGISCTA000006195589' and `debut` <= '2018-12-06' and (`fin` > '2018-12-06' or `fin` = '2018-12-06' or `etat` = 'VIGUEUR') order by `position` asc`.

<img width="1003" alt="capture d ecran 2018-12-06 a 15 04 13" src="https://user-images.githubusercontent.com/124937/49588897-3cfe1680-f968-11e8-9d96-d3d38d69eb44.png">

**Comment by Changaco** [comment]
@revolunet Ta base SQLite a-t-elle été créée avant le 6 juillet ?

Je pense qu'en fait quand une nouvelle archive globale est publiée il faut recréer la base SQLite depuis zéro, ce que legi.py ne fait pas actuellement, sinon on se retrouve avec des éléments manquants voire au contraire avec des éléments obsolètes. Ça expliquerait pourquoi le nombre d'anomalies détectées a explosé depuis juillet, un phénomène qui s'était d'ailleurs déjà produit après la publication de la précédente archive globale, si ma mémoire est bonne.

**Comment by Changaco** [comment]
Ticket précédent sur le même sujet : <https://github.com/Legilibre/Archeo-Lex/issues/30>.

**Comment by revolunet** [comment]
Merci je check ça

**Comment by revolunet** [comment]
Bien vu c'est bien le cas 👌
