### ISSUE TITLE
Nouveau type d’anomalie : article référencé mais manquant

### ISSUE THREAD

**Issue by Seb35** [Legilibre/legi.py#5]
Dans la base LEGI, parfois, un code référence dans son sommaire (fichier SCTA) un article mais la description de l’article (le fichier ARTI) manque. Cela est par exemple arrivé pour LEGIARTI000033706110 référencé dans la section LEGISCTA000018780362 (code de l’action sociale et des familles LEGITEXT000006074069) dans la version 20170224-204824 de la base LEGI.

Il pourrait être intéressant de détecter ce type d’anomalie : article référencé dans un sommaire mais sa description manque (c’est-à-dire notamment son texte). Cela serait l’inverse des "articles orphelins".

Voir aussi https://github.com/Legilibre/Archeo-Lex/issues/30 : lorsque qu’un article manque, l’export avec Archéo Lex plante à juste titre.

**Comment by Changaco** [comment]
J'ai une première version. Résultat : 815 anomalies supplémentaires détectées ! 645 références à des articles introuvables, et 170 à des sections.

**Comment by Changaco** [comment]
Les changements sont intégrés (voir #6), il ne reste plus qu'à recréer les listes d'anomalies depuis le début.

**Comment by Seb35** [comment]
Bravo ! J’attends avec impatience la mise en prod :)

Pour info, je suis en train de faire tourner legi.py (tar2sqlite) depuis le début en vue de l’utiliser dans Archéo Lex.

**Comment by Changaco** [comment]
@Seb35 Note que si tu as lancé tar2sqlite à partir de la branche `master` ta base sera recrée depuis le début quand #8 sera intégré.

Tu devrais t'abonner au dépôt pour suivre toute l'activité du projet.

**Comment by Changaco** [comment]
Les nouvelles listes d'anomalies sont en ligne : http://anomalies.legilibre.fr/
