### ISSUE TITLE
Python 3.4

### ISSUE THREAD

**Issue by Seb35** [Legilibre/legi.py#55]
À la suite de #30, il est indiqué que la version minimum de Python est 3.6 ou 3.7. J’ai sur ma machine Python 3.4 qui génère une erreur minime dans `legi/french.py` dans la variable `short_ordinals_p` où la synaxe `(?-i:)` a été introduite [dans Python 3.6](https://docs.python.org/3/library/re.html#index-16).

Étant donné que ça semble être la seule limitation et qu’il y a moyen de se passer de cette syntaxe en utilisant un flag dans `short_ordinal_re`, je propose d’autoriser le Python 3.4.

Je peux m’occuper de faire la requête d’intégration (_pull request_) en changeant cette syntaxe et en ajoutant l’intégration continue pour Python 3.4.

**Comment by Changaco** [comment]
Non merci. On est enfin débarrassé de Python 2.7, on ne va recommencer à perdre du temps et à polluer le code pour supporter à nouveau des versions obsolètes de Python.

La gestion fine de la casse dans les expression régulières est parfois utile, car ignorer la casse dans toute une expression peut rendre celle-ci trop « indulgente » et mener à des faux positifs.

**Comment by Seb35** [comment]
Je ferme cette issue. La dernière version de Debian, 10 (Buster), contient Python 3.7.3, que j’utilise désormais. Et vu que, en un an personne, n’a demandé sur cette issue, ça ne doit pas gêner.
