### ISSUE TITLE
Soft hyphens (SHY)

### ISSUE THREAD

**Issue by Changaco** [Legilibre/legi.py#56]
En travaillant sur la détection des liens (#4) je me suis rendu compte que LEGI contient des [soft hyphens](https://en.wikipedia.org/wiki/Soft_hyphen) dont il faudrait se débarrasser.

**Comment by Seb35** [comment]
Sur les tirets, je me suis heurté au cas également pour la détection de liens (cf [cette règle](https://framagit.org/parlement-ouvert/metslesliens/blob/aeb1f8d80b3a458f4dd3cd0efa9fbfdf28fcf330/metslesliens/grammaire-liens.txt#L95) avec trois tirets), et j’ai aussi une normalisation dans Archéo Lex (cf [cette regex](https://github.com/Legilibre/Archeo-Lex/blob/5070e524655c3db4e9fdc3c3329838d48a6a8975/marcheolex/exports/Markdown.py#L66) avec 7 tirets).
