### ISSUE TITLE
Des tabulations qui trainent dans le code de la sécurité sociale

### ISSUE THREAD

**Issue by mdamien** [Legilibre/legi.py#71]
Bonjour tout le monde, en travaillant sur le code de la sécurité sociale, j'ai découvert deux mini-bugs de formatage: 

Le premier, la section 9 du chapitre 1er du titre 9 du livre 3, "Personnes retenues dans un centre socio-médico-judiciaire de sûreté". 

![image](https://user-images.githubusercontent.com/1469823/72620232-34378c80-393f-11ea-968b-4713ebaf984d.png)

- [Le texte brut où l'on peut constater le bug](https://archeo-lex.fr/codes/code_de_la_s%C3%A9curit%C3%A9_sociale/2019-08-14/brut)
- [La section sur Legifrance](https://www.legifrance.gouv.fr/affichCode.do;jsessionid=DE42C9137048517B6BA170E6A9AFA149.tplgfr36s_1?idSectionTA=LEGISCTA000018171095&cidTexte=LEGITEXT000006073189&dateTexte=20080227)

J'ai vu un bug similaire dans l'article `D221-29` d'ailleurs.

![image](https://user-images.githubusercontent.com/1469823/72620163-09e5cf00-393f-11ea-9f42-87cdd883bcc5.png)

Bon, le bug n’apparaît pas dans la version HTML, du coup c'est quand même très mineur.

A priori, le bug est sur `legi.py`, même si je l'ai découvert en allant sur Archeolex.

Ca rapelle La Fabrique, on avait décidé d'enlever tout les doubles-espaces si je me rappel bien.

Ma solution serait surement de rajouter une regex ici:

https://github.com/Legilibre/Archeo-Lex/blob/044b6ac726571e38a4770d4392c9e8edef0088cb/marcheolex/exports/Markdown.py#L145

Du style `texte = re.sub( r'\s+', ' ', texte )`.

**Comment by Changaco** [comment]
Le nettoyage des contenus n'est pas encore activé par défaut, il faut lancer `python -m legi.html clean legi.sqlite` et appuyer sur `y` à la fin pour enregistrer les modifications. J'aimerais régler #56 avant d'intégrer le nettoyage HTML à `tar2sqlite`.

La normalisation des titres de sections n'est pas non plus effectuée par défaut, mais je ne sais pas pourquoi. J'ai peut-être tout simplement oublié de l'ajouter à `tar2sqlite`.

**Comment by mdamien** [comment]
D'accord, alors ca m'a plutôt l'air d'être aussi lié à Archeolex alors, merci :)

**Comment by mdamien** [comment]
Toujours en parlant de normalisation, j'ai trouvé un autre petit souci:

A l'article [R-241-0-4](https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000006748738&cidTexte=LEGITEXT000006073189&dateTexte=20051103), le dernier alinéa finit par un point mais pas dans la version sur Archeolex, voila voila.

![image](https://user-images.githubusercontent.com/1469823/72764380-1e98c000-3be8-11ea-9e32-1921d65c2d0d.png)

**Comment by Changaco** [comment]
legi.py nettoie désormais l'HTML et les traits d'union conditionnels par défaut (#76 et #77).
