### ISSUE TITLE
Articles manquants dans le code de la sécurité sociale

### ISSUE THREAD

**Issue by mdamien** [Legilibre/legi.py#75]
Re-bonjour/bonsoir,

Toujours en parcourant le code la sécurité sociale, j'ai vu que la section 3 du chapitre II du livre II est vide dans [la version sur Archeolex](https://archeo-lex.fr/codes/code_de_la_s%C3%A9curit%C3%A9_sociale/2019-08-14) mais elle existe bien [sur Légifrance](https://www.legifrance.gouv.fr/affichCode.do;jsessionid=3D9F97E12A44524819CF073EE7C06E68.tplgfr36s_1?idSectionTA=LEGISCTA000006172583&cidTexte=LEGITEXT000006073189&dateTexte=20080227).

![image](https://user-images.githubusercontent.com/1469823/72762588-76cbc400-3be0-11ea-8258-3a7639e71668.png)

En éspérant que ca aide

**Comment by Changaco** [comment]
Cette section et ses articles sont présents dans ma base SQLite.

```sql
SELECT count(*)
  FROM sommaires s
  JOIN articles a ON a.id = s.element
 WHERE s.cid = 'LEGITEXT000006073189' AND s.parent = 'LEGISCTA000006172583';
```

La base d'Archeolex a probablement besoin d'être recrée à partir de zéro avec #74. Ping @Seb35.
